### ISSUE TITLE
unsupported flash type: 85401285

### ISSUE THREAD

**Issue by someplaceguy** [BertoldVdb/jms578flash#6]
Hi,

> If you get an 'unsupported flash type: 00112233' error, you will need to add the commands for your chip to spiflash/types.go

> If you do not know how to do this you can open a ticket for it.

I just got the mentioned error, but unfortunately I have no idea how to add the commands for my chip. In fact, I don't even know what chip I have.

What can I do to find out?

**Comment by BertoldVdb** [comment]
Hello,

Can you tell me the flash id you got? I can try to find it.

Sincerely,
Bertold

Op zo 6 aug. 2023 07:16 schreef someplaceguy ***@***.***>:

**Comment by someplaceguy** [comment]
> Hello, Can you tell me the flash id you got? I can try to find it.

I think the flash ID you are referring to is in the title of this issue (which is the exact error message that I received): `85401285`.

If you are referring to some other ID, can you tell me how to find out this ID?

I'm a bit out of my depth here... :)

**Comment by BertoldVdb** [comment]
Hello,

Sorry, I didn't see this. I think this chip is made by PUYA, I found the exact device: P25Q21H. You can get the datasheet here: https://datasheet.lcsc.com/lcsc/1912111437_PUYA--P25Q21H-SSH-IT_C414061.pdf

I will add the definition this evening and you can test it. Please read out the firmware first before doing anything else.

Sincerely,
Bertold

**Comment by BertoldVdb** [comment]
I have added the chip: https://github.com/BertoldVdb/jms578flash/blob/master/spiflash/types.go#L22

Good luck.

**Comment by someplaceguy** [comment]
Thanks!

It seems to work partially, although I think something strange happened:

1. First, I extracted the firmware, which seems to have worked fine.
2. Second, I dumped the BootROM, which also seems to have worked fine.

At this point the firmware was wiped, as mentioned in the README.md (although I didn't realize this would happen because I had forgotten the big bold uppercase-letter warning).

3. I've tried to flash back the same firmware, but this happened:
```
2023/08/08 12:02:16 Failed to write flash: bootrom is not known to this library
```

4. I've tried to dump the BootROM again, which seems to have worked fine.
5. However, when I compare this second dump against the first dump, the files are different. In the first dump I don't see any recognizable pattern (almost all of it looks like random data, except for some consecutive sequences of zeros), but in the second dump I can see strings such as `51.1JMICRON.JMS579` and `JMicron JMS579`. So it seems that the first dump got corrupted data, somehow.
6. I've tried to flash a firmware using the second BootROM dump, but now this is the problem I'm having:

```
$ ./jms578flash -flash -firmware fw.bin -bootrom ./boot_rom.bin -mods ClearNVRAM
2023/08/08 12:06:02 Failed to write flash: patched bootrom did not start running
```

Any ideas? 

BTW, I hadn't realized that this was a JMS579 bridge until I looked at the contents of the second dump. All the materials from the vendor indicate that this adapter was supposed to have a JMS578 bridge, and I missed the kernel message which indeed says that it's a JMS579.

**Comment by BertoldVdb** [comment]
Hi, 

JMS578 and JMS579 are nearly identical, this should not be the issue. Seems something went wrong when dumping the ROM the first time, likely related to the firmware that was running. Since the 'bootrom is not known to this library' error went away you have certainly dumped it correctly and it is a known version.

Did you try to power cycle the device? What do you see in dmesg after starting the flash write command?

Note that you can flash firmware without the bootrom argument, it will just be much slower.

**Comment by someplaceguy** [comment]
> Did you try to power cycle the device?

Yes. I tried again to power cycle the device and flash the firmware, but the same problem happened.

> What do you see in dmesg after starting the flash write command?

When I try to flash the firmware using the BootROM, I just see a normal USB disconnect and reconnect.

> Note that you can flash firmware without the bootrom argument, it will just be much slower.

Oh, right, I had forgotten about that too...

I've made sure to power cycle the device (i.e. disconnect and reconnect the USB cable) and then this is what I did:

```
$ ./jms578flash -flash -firmware original_fw.bin
2023/08/08 12:48:06 SPI access: 9f -> 85401285
2023/08/08 12:48:06 SPI access: 03000e00 -> 0100152d0579030305054a4d
2023/08/08 12:48:06 SPI access: 03000e0c -> 6963726f6e204a4d53353739
2023/08/08 12:48:06 SPI access: 03000e18 -> 013031303300000000000000
2023/08/08 12:48:06 SPI access: 03000e24 -> 000000000000000000000000
2023/08/08 12:48:06 SPI access: 03000e30 -> 000000000000000000000000
(...)
2023/08/08 12:48:06 SPI access: 03000fe0 -> 000000000000000000000000
2023/08/08 12:48:06 SPI access: 03000fec -> 000000000000000000000000
2023/08/08 12:48:06 SPI access: 03000ff8 -> 00000000d4e89ea0
2023/08/08 12:48:06 SPI access: 03000000 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 0300000c -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03000018 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03000024 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03000030 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 0300003c -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03000048 -> ffffffffffffffffffffffff
(...)
2023/08/08 12:48:06 SPI access: 030001e0 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 030001ec -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 030001f8 -> ffffffffa528c58d
2023/08/08 12:48:06 SPI access: 03001000 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 0300100c -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001018 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001024 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001030 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 0300103c -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001048 -> ffffffffffffffffc2019070
2023/08/08 12:48:06 SPI access: 03001054 -> 8c7407f0e490411af0a3f0a3
2023/08/08 12:48:06 SPI access: 03001060 -> f0a3f0a3fbfffefd7c80121f
2023/08/08 12:48:06 SPI access: 0300106c -> 1b0c0ebe40f890705474e1f0
2023/08/08 12:48:06 SPI access: 03001078 -> 22ffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001084 -> ffffffffffffffffffffffff
2023/08/08 12:48:06 SPI access: 03001090 -> ffffffffffffffffffffffff
(...)
2023/08/08 12:48:16 SPI access: 0300d1e0 -> ffffffffffffffffffffffff
2023/08/08 12:48:16 SPI access: 0300d1ec -> ffffffffffffffffffffffff
2023/08/08 12:48:16 SPI access: 0300d1f8 -> ffffffffffffffff
2023/08/08 12:48:16 Failed to write flash: flash write requires unsafeAllow=true
```

I've abbreviated all the lines that contain repeated information, except for the increasing number (offset?).

Perhaps it's not clear due to the abbreviation, but I mostly see a bunch of `ffffffffffffffffffffffff`. And also, of course, the error message at the end.

The kernel log shows something different for this command:

```
2023-08-08T11:48:16.547275+00:00 laptop kern.notice kernel: sd 0:0:0:0: [sda] Unit Not Ready
2023-08-08T11:48:16.547299+00:00 laptop kern.info kernel: sd 0:0:0:0: [sda] Sense Key : Illegal Request [current]
2023-08-08T11:48:16.547306+00:00 laptop kern.info kernel: sd 0:0:0:0: [sda] Add. Sense: Invalid command operation code
2023-08-08T11:48:16.549269+00:00 laptop kern.info kernel: sd 0:0:0:0: [sda] Read Capacity(10) failed: Result: hostbyte=DID_OK driverbyte=DRIVER_OK
2023-08-08T11:48:16.549285+00:00 laptop kern.info kernel: sd 0:0:0:0: [sda] Sense Key : Illegal Request [current]
2023-08-08T11:48:16.549293+00:00 laptop kern.info kernel: sd 0:0:0:0: [sda] Add. Sense: Invalid command operation code
```

Any ideas?

**Comment by someplaceguy** [comment]
Never mind, it's clear that today is not my brightest day. I was just missing the `-unsafe` option!

I have now written back the original firmware and it worked! Not only the command succeeded, but the device came back to life and I can access the disk again.

Thanks for all the help and feel free to close the issue!

**Comment by BertoldVdb** [comment]
Super
